---
- name: installation of firewall package and allowing httpd service
  hosts: 
  - america
  - africa
  serial: 2
  tasks:
  - name: installing the firewalld
    yum: 
      name: firewalld
      state: present
  
  - name: start the firewall service
    service: 
      name: firewalld
      state: started
      enabled : true


